config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  namespace :admin do
    resources :users
  end

  mount Sidekiq::Web => "/sidekiq"

  namespace :api, defaults: { format: :json } do
    resources :users, only: :show
  end

  root to: "home#index"

  if ENV.fetch("RAILS_ENV", "development") == "production"
    match "*unmatched", to: "errors#not_found", via: :all, constraints: lambda { |req|
      req.path.exclude?("rails/active_storage")
    }
  end
end

app/views/shared/_flash_messages.html.erb
<% if flash[:alert] || flash[:warning] || flash[:notice] %>
  <div class="space-y-4 <%= defined?(container_class) ? container_class : "" %>">
    <% if flash[:alert] %>
      <%= react_component :FlashMessage, variant: :danger, children: flash[:alert] %>
    <% end %>
    <% if flash[:warning] %>
      <%= react_component :FlashMessage, variant: :warning, children: flash[:warning] %>
    <% end %>
    <% if flash[:notice] %>
      <%= react_component :FlashMessage, variant: :success, children: flash[:notice] %>
    <% end %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="bg-white shadow-sm sticky inset-x-0">
  <div class="container mx-auto">
    <div class="flex justify-between flex-wrap">
      <div class="flex">
        <%= link_to root_path, class: "md:mr-12 grid" do %>
          <%= image_pack_tag "images/muffi-logo.svg", class: "justify-self-center self-center" %>
        <% end %>
      </div>

      <div class="md:hidden flex items-center">
        <button class="focus:outline-none py-4 px-4" onclick="this.closest('nav').querySelector('ul').classList.toggle('hidden')">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
      </div>

      <ul class="w-full md:w-auto md:flex-grow md:flex items-center hidden md:space-x-5">
        <% if user_signed_in? %>
          <% if policy(:user).index? %>
            <li>
              <%= link_to t(".users"), admin_users_path, class: "NavLink #{'NavLink--active' if controller_name == 'users'}" %>
            </li>
          <% end %>
        <% end %>

        <li class="md:flex-grow"></li>

        <li>
          <% if user_signed_in? %>
            <%= link_to t(".sign_out"), destroy_user_session_path, method: :delete, class: "NavLink" %>
          <% else %>
            <%- if controller_name != 'sessions' %>
              <%= link_to t(".log_in"), new_session_path(User), class: "NavLink" %>
            <% end %>
            <%- if Devise.mappings[:user].registerable? && controller_name != 'registrations' %>
              <%= link_to t(".sign_up"), new_registration_path(User), class: "NavLink" %>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>