config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  namespace :admin do
    resources :users
  end

  mount Sidekiq::Web => "/sidekiq"

  namespace :api, defaults: { format: :json } do
    resources :users, only: :show
  end

  root to: "home#index"

  if ENV.fetch("RAILS_ENV", "development") == "production"
    match "*unmatched", to: "errors#not_found", via: :all, constraints: lambda { |req|
      req.path.exclude?("rails/active_storage")
    }
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include ApiAuthenticable

  # Included devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :pwned_password
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < BaseController
    def index
      @users = policy_scope(authorize(User))
    end

    def show
      @user = authorize(User.find(params[:id]))
    end

    def new
      @user = authorize(User.new)
    end

    def edit
      @user = authorize(User.find(params[:id]))
    end

    def create
      @user = authorize(User.new(permitted_attributes(User)))

      if @user.save
        flash[:notice] = I18n.t("shared.flash_messages.success")

        redirect_to admin_user_path(@user)
      else
        flash.now[:alert] = I18n.t("shared.flash_messages.error")

        render :new
      end
    end

    def update
      @user = authorize(User.find(params[:id]))

      if @user.update(update_params)
        flash[:notice] = I18n.t("shared.flash_messages.success")

        redirect_to admin_user_path(@user)
      else
        flash.now[:alert] = I18n.t("shared.flash_messages.error")

        render :edit
      end
    end

    def destroy
      user = authorize(User.find(params[:id]))

      if user.destroy
        flash[:notice] = I18n.t("shared.flash_messages.success")
      else
        flash[:alert] = I18n.t("shared.flash_messages.error")
      end

      redirect_to admin_users_path
    end

    private

    def update_params
      permitted_attributes(@user).tap do |params|
        if params["password"].blank? && params["password_confirmation"].blank?
          params.delete("password")
          params.delete("password_confirmation")
        end
      end
    end
  end
end

app/controllers/api/users_controller.rb
# frozen_string_literal: true

module Api
  class UsersController < Api::BaseController
    before_action :require_authentication!

    def show
      render json: UserSerializer.new(current_user).serializable_hash
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= back_path_field %>
  <div class="mb-6">
    <%= f.label(:email, class: "inline-block mb-2") %>
    <%= f.email_field(:email, placeholder: true, class: "Input Input--default Input--md block w-full") %>
    <%= field_error(field: :email, resource: @user) %>
  </div>
  <div class="mb-6">
    <%= f.label(:name, class: "inline-block mb-2") %>
    <%= f.text_field(:name, placeholder: true, class: "Input Input--default Input--md block w-full") %>
    <%= field_error(field: :name, resource: @user) %>
  </div>
  <div class="mb-6">
    <%= f.label(:password, class: "inline-block mb-2") %>
    <%= f.password_field(:password, autocomplete: "new-password", placeholder: true, class: "Input Input--default Input--md block w-full") %>
    <%= field_error(field: :password, resource: @user) %>
  </div>
  <div class="mb-10">
    <%= f.label(:password_confirmation, class: "inline-block mb-2") %>
    <%= f.password_field(:password_confirmation, autocomplete: "new-password", placeholder: true, class: "Input Input--default Input--md block w-full") %>
    <%= field_error(field: :password_confirmation, resource: @user) %>
  </div>
  <div class="flex justify-end">
    <button type="submit" class="Button Button--md Button--primary"><%= t("admin.shared.save") %></button>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container mx-auto my-20 max-w-3xl">
  <div class="flex items-center">
    <h1 class="text-3xl flex-grow"><%= t(".title", title: @user.email) %></h1>

    <%= link_to t("admin.shared.back"), back_path(fallback: admin_users_path), class: "ButtonClear ButtonClear--md ButtonClear--primary" %>
  </div>

  <div class="rounded border border-neutral-200 shadow-sm mt-10 p-5 bg-white">
    <%= render partial: "form" %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container mx-auto my-20">
  <div class="flex items-center">
    <h1 class="text-3xl flex-grow"><%= t(".title") %></h1>

    <% if policy(User).new? %>
      <%= link_to t(".new"), new_admin_user_path, class: "Button Button--sm Button--primary" %>
    <% end %>
  </div>

  <div class="overflow-hidden rounded border border-neutral-200 shadow-sm mt-10">
    <table class="min-w-full">
      <thead class="border-b border-b-neutral-200">
        <tr class="bg-neutral-50">
          <th scope="col" class="text-left text-neutral-500 text-xs uppercase font-medium px-6 py-3">
            <%= User.human_attribute_name("email") %>
          </th>
          <th scope="col" class="text-left text-neutral-500 text-xs uppercase font-medium px-6 py-3">
            <%= User.human_attribute_name("name") %>
          </th>
          <th scope="col" class="text-left text-neutral-500 text-xs uppercase font-medium px-6 py-3">
            <%= User.human_attribute_name("created_at") %>
          </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr class="even:bg-neutral-50 odd:bg-white">
            <td class="text-sm text-neutral-800 font-medium px-3 py-2 whitespace-nowrap">
              <% if policy(user).show? %>
                <%= link_to user.email, admin_user_path(user), class: "ButtonClear ButtonClear--sm ButtonClear--primary" %>
              <% else %>
                <span class="ButtonClear ButtonClear--sm">
                  <%= user.email %>
                </span>
              <% end %>
            </td>
            <td class="text-sm text-neutral-500 px-6 py-4 whitespace-nowrap">
              <%= user.name %>
            </td>
            <td class="text-sm text-neutral-500 px-6 py-4 whitespace-nowrap">
              <%= I18n.l(user.created_at, format: :short) %>
            </td>
            <td scope="row" class="px-3 py-2 flex justify-end">
              <% if policy(user).edit? %>
                <%= link_to t("admin.shared.edit"), edit_admin_user_path(user), class: "ButtonClear ButtonClear--sm ButtonClear--primary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container mx-auto my-20 max-w-3xl">
  <div class="flex items-center">
    <h1 class="text-3xl flex-grow"><%= t(".title") %></h1>

    <%= link_to t("admin.shared.back"), back_path(fallback: admin_users_path), class: "ButtonClear ButtonClear--md ButtonClear--primary" %>
  </div>

  <div class="rounded border border-neutral-200 shadow-sm mt-10 p-5 bg-white">
    <%= render partial: "form" %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container mx-auto my-20 max-w-3xl">
  <div class="flex items-center">
    <h1 class="text-3xl flex-grow"><%= @user.email %></h1>

    <% if policy(User).index? %>
      <%= link_to t("admin.shared.back"), admin_users_path, class: "ButtonClear ButtonClear--md ButtonClear--primary mr-2" %>
    <% end %>
    <% if policy(@user).edit? %>
      <%= link_to t("admin.shared.edit"), edit_admin_user_path(@user), class: "ButtonClear ButtonClear--md ButtonClear--primary mr-2" %>
    <% end %>
    <% if policy(@user).destroy? %>
      <%= link_to t("admin.shared.delete"), admin_user_path(@user), method: :delete, data: { confirm: t("admin.shared.delete_confirm") }, class: "Button Button--md Button--danger" %>
    <% end %>
  </div>

  <div class="overflow-hidden rounded border border-neutral-200 shadow-sm mt-10">
    <table class="min-w-full">
      <tbody>
        <tr class="even:bg-neutral-50 odd:bg-white">
          <th class="text-left text-neutral-500 text-xs uppercase font-medium px-6 py-3">
            <%= User.human_attribute_name("email") %>
          </th>
          <td class="text-sm text-neutral-800 font-medium px-3 py-2 whitespace-nowrap">
            <%= @user.email %>
          </td>
        </tr>

        <tr class="even:bg-neutral-50 odd:bg-white">
          <th class="text-left text-neutral-500 text-xs uppercase font-medium px-6 py-3">
            <%= User.human_attribute_name("name") %>
          </th>
          <td class="text-sm text-neutral-800 font-medium px-3 py-2 whitespace-nowrap">
            <%= @user.name %>
          </td>
        </tr>

        <tr class="even:bg-neutral-50 odd:bg-white">
          <th class="text-left text-neutral-500 text-xs uppercase font-medium px-6 py-3">
            <%= User.human_attribute_name("created_at") %>
          </th>
          <td class="text-sm text-neutral-800 font-medium px-3 py-2 whitespace-nowrap">
            <%= I18n.l(@user.created_at, format: :short) %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>